name: ledger_cli_flutter
description: Flutter components for displaying ledger-cli data
version: 0.2.0
homepage: https://github.com/amos-joshua/ledger_cli_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ledger_cli: #^0.1.1
    path: ../ledger-cli-dart
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
