name: ledger_cli_flutter
description: Flutter components for displaying ledger-cli data
version: 0.1.0
homepage: https://github.com/amos-joshua/ledger_cli_flutter

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ledger_cli: ^0.1.1
    #path: ../ledger-cli-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
